//! Datastore adapters implementing [`crate::engine::BenchmarkEngine`] and [`crate::engine::BenchmarkClient`].

#[cfg(feature = "arangodb")]
pub(crate) mod arangodb;
#[cfg(feature = "dragonfly")]
pub(crate) mod dragonfly;
pub(crate) mod dry;
#[cfg(feature = "fjall")]
pub(crate) mod fjall;
#[cfg(feature = "keydb")]
pub(crate) mod keydb;
#[cfg(feature = "lmdb")]
pub(crate) mod lmdb;
pub(crate) mod map;
#[cfg(feature = "mariadb")]
pub(crate) mod mariadb;
#[cfg(feature = "mdbx")]
pub(crate) mod mdbx;
#[cfg(feature = "mongodb")]
pub(crate) mod mongodb;
#[cfg(feature = "mysql")]
pub(crate) mod mysql;
#[cfg(feature = "neo4j")]
pub(crate) mod neo4j;
#[cfg(feature = "postgres")]
pub(crate) mod postgres;
#[cfg(feature = "redb")]
pub(crate) mod redb;
#[cfg(feature = "redis")]
pub(crate) mod redis;
#[cfg(feature = "rocksdb")]
pub(crate) mod rocksdb;
#[cfg(feature = "scylladb")]
pub(crate) mod scylladb;
#[cfg(feature = "slatedb")]
pub(crate) mod slatedb;
#[cfg(feature = "sqlite")]
pub(crate) mod sqlite;
#[cfg(feature = "surrealdb")]
pub(crate) mod surrealdb;
#[cfg(feature = "surrealdb2")]
pub(crate) mod surrealdb2;
#[cfg(feature = "surrealdb")]
pub(crate) mod surrealds;
#[cfg(feature = "surrealkv")]
pub(crate) mod surrealkv;
#[cfg(feature = "surrealmx")]
pub(crate) mod surrealmx;
